# This is a basic workflow to help you get started with Actions

name: IPTV-Proxy CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    types: [closed]
    branches: [master]
  watch:
    types: [started]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REGISTRY_URL: docker.io
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/iptv-proxy
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create image Flag
        run: |
          export FLAG=$(date +%s)
          echo "FLAG=$FLAG" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
        #  platforms: linux/arm64,linux/arm/v7 
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@34d5f75b0d6d0d22f06d83acf2fa1b144409ec83
        uses: docker/login-action@v1.4.1
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ env.DOCKER_REGISTRY_URL }} # optional
          # Username used to log against the Docker registry
          username: ${{ env.DOCKER_USERNAME }} # optional
          # Password or personal access token used to log against the Docker registry
          password: ${{ env.DOCKER_PASSWORD }} 
          # Log out from the Docker registry at the end of a job
          logout: true # optional, default is true

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          # Path to the build context
          context: . # optional, default is .
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
          file: ./Dockerfile # optional
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.FLAG }}
          platforms: |
            linux/arm64
            linux/arm/v7
          push: true # optional, default is true
